export const SHIPMENT_STATUSES = {
  PENDING: "PENDING",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
} as const

export const USER_ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const

export const JWT_CONFIG = {
  EXPIRES_IN: "7d",
  ALGORITHM: "HS256",
} as const

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
} as const
